name: socks5
description: Simple SOCKS5 connection initializer using RawSocket, supports connection requests by Ip and Domain
version: 0.1.2
homepage: https://github.com/v0l/socks

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter